### ISSUE TITLE
Change pin integration test is unstable

### ISSUE THREAD

**Issue by ivard** [privacybydesign/irmamobile#248]
The test fails half of the time with the following error:

```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
The finder "zero widgets with text "Prefer a shorter PIN?"
(considering only hit-testable ones) (ignoring offstage widgets)"
(used in a call to "tap()") could not find any matching widgets.
When the exception was thrown, this was the stack:
#0 WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1294:7)
#1 WidgetController.getCenter (package:flutter_test/src/controller.dart:1233:12)
#2 WidgetController.tap (package:flutter_test/src/controller.dart:554:18)
#3 WidgetTesterUtil.tapAndSettle (file:///home/runner/work/irmamobile/irmamobile/integration_test/util.dart:15:11)
#4 main.<anonymous closure>.<anonymous closure> (file:///home/runner/work/irmamobile/irmamobile/integration_test/settings_test.dart:231:20)
<asynchronous suspension>
#5 testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:165:15)
<asynchronous suspension>
#6 TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:982:5)
<asynchronous suspension>
The test description was:
change-pin
```

**Comment by ivard** [comment]
Pixel 6a in Google Firebase Test Lab:

![image](https://github.com/privacybydesign/irmamobile/assets/17035191/c1c0d052-86be-426a-850f-027edb70de8e)
